export const PreferenciasLabels = {
  PLAYA: "Playa",
  MONTANA: "Montaña",
  CIUDAD: "Ciudad",
  CALUROSO: "Caluroso",
  TEMPLADO: "Templado",
  FRIO: "Frío",
  DEPORTES_Y_AVENTURAS: "Deportes y Aventuras",
  CULTURA_Y_MUSEOS: "Cultura y Museos",
  RELAX_Y_BIENESTAR: "Relax y Bienestar",
  HOTEL_LUJO: "Hotel de lujo",
  HOSTAL_ALBERGUE: "Hostal/Albergue",
  AIRBNB: "Airbnb",
  MENOR_UNA_SEMANA: "Menos de una semana",
  UNA_Y_DOS_SEMANAS: "Entre una y dos semanas",
  MAYOR_DOS_SEMANAS: "Más de dos semanas",
  MENOR_QUE_TREINTA: "Menos de 30",
  TREINTA_Y_CINCUENTA: "Entre 30 y 50",
  MAYOR_QUE_CINCUENTA: "Más de 50",
};